import type { PromptItem } from "@/lib/types";

/**
 * "Prompte të Fuqishme për Gruan Shqiptare" — the full pack, mapped to the 18+
 * library categories. Bodies are kept in natural Albanian as templates with
 * [bracketed] fields; titles/descriptions are bilingual. The AI replies in the
 * user's chosen language.
 */
export const PROMPT_PACK: PromptItem[] = [
  // ---------- Master prompt (featured) ----------
  {
    id: "personal-advisor",
    category: "confidence",
    icon: "Crown",
    featured: true,
    title: { sq: "Këshilltarja personale", en: "Your personal advisor" },
    description: {
      sq: "Prompti më i fortë — të bën pyetje e pastaj të jep një plan vetëm për ty.",
      en: "The most powerful prompt — it asks you questions, then gives a plan just for you.",
    },
    body: "Dua të jesh këshilltarja ime personale. Para se të më japësh këshilla, më bëj pyetje për të kuptuar situatën time, qëllimet dhe vështirësitë. Pyetmë një nga një. Pasi të kesh një pamje të qartë, më jep një plan personal me hapa konkretë, të përshtatur për jetën time si grua [me/pa fëmijë, e punësuar/jo, etj.]. Ji e drejtpërdrejtë, e ngrohtë dhe praktike — jo e përgjithshme.",
  },

  // ---------- 1. Punë dhe Karrierë ----------
  {
    id: "career-plan-12m",
    category: "career",
    icon: "Target",
    title: { sq: "Plani yt i karrierës për një vit", en: "A 12-month career plan" },
    description: { sq: "Hapa muaj pas muaji dhe një gjë që mund ta nisësh sot.", en: "Month-by-month steps and one thing to start today." },
    body: "Vepro si një këshilltare karriere me përvojë. Unë jam [mosha], punoj si [pozicioni aktual] në fushën e [fusha]. Dëshiroj të [qëllimi: ngritje në detyrë / ndryshim karriere / rritje page]. Më ndihmo të ndërtoj një plan konkret 12-mujor me hapa mujorë, aftësi që duhet të mësoj, dhe 3 rreziqe që duhet të shmang. Përfundo me një hap të vetëm që mund ta bëj sot.",
  },
  {
    id: "career-raise",
    category: "career",
    icon: "TrendingUp",
    title: { sq: "Si të kërkosh rritje page", en: "How to ask for a raise" },
    description: { sq: "Çfarë t'i thuash shefit dhe si të përgjigjesh nëse të thotë jo.", en: "What to say to your boss and how to respond to a 'no'." },
    body: "Më ndihmo të përgatis një bisedë për rritje page me menaxherin tim. Roli im: [pozicioni]. Arritjet e mia kryesore: [listo 2–3]. Paga aktuale: [shuma], paga që kërkoj: [shuma]. Më jep një skenar bisede, fjalët e sakta që mund të përdor, dhe si t'i përgjigjem nëse më thotë 'jo'.",
  },
  {
    id: "career-impostor",
    category: "career",
    icon: "Sparkles",
    title: { sq: "Kur ndihesh se nuk e meriton", en: "When you feel you don't deserve it" },
    description: { sq: "Kupto nga vjen kjo ndjenjë dhe një fjalë për veten para çdo takimi.", en: "Understand the feeling and a phrase for before every meeting." },
    body: "Shpesh ndihem sikur nuk e meritoj pozicionin tim edhe pse [konteksti]. Më ndihmo të kuptoj nga vjen kjo ndjenjë, më jep 3 mënyra praktike për ta menaxhuar, dhe një frazë që mund t'ia them vetes para çdo takimi të rëndësishëm.",
  },
  {
    id: "career-say-no",
    category: "career",
    icon: "MessageCircle",
    title: { sq: "Si të thuash 'jo' në punë", en: "How to say 'no' at work" },
    description: { sq: "Mënyra të sjellshme për të refuzuar pa prishur punë.", en: "Polite ways to decline without straining things." },
    body: "Më mësojnë gjithmonë detyra shtesë dhe e kam të vështirë të refuzoj. Më jep 5 mënyra të sjellshme por të qarta për të thënë 'jo' ose 'jo tani' në punë, pa dëmtuar marrëdhëniet me kolegët.",
  },

  // ---------- 2. CV, LinkedIn dhe Intervista ----------
  {
    id: "cv-from-scratch",
    category: "cv",
    icon: "FileText",
    title: { sq: "Bëje CV-në nga e para", en: "Build your CV from scratch" },
    description: { sq: "Një CV e qartë, me një përmbledhje të fortë dhe arritjet e tua.", en: "A clear CV with a strong summary and your achievements." },
    body: "Vepro si ekspert/e rekrutimi. Më ndihmo të shkruaj një CV profesionale për pozicionin [pozicioni i synuar]. Përvoja ime: [përshkruaj punët e mëparshme]. Aftësitë e mia: [listo]. Arsimimi: [shkolla/universiteti]. Shkruaje CV-në me një përmbledhje të fortë në krye dhe pikat e arritjeve që fillojnë me folje veprimi.",
  },
  {
    id: "cv-improve",
    category: "cv",
    icon: "PenLine",
    title: { sq: "Përmirëso CV-në që ke", en: "Improve the CV you have" },
    description: { sq: "Çfarë të ndryshosh që të duket më e fortë.", en: "What to change so it looks stronger." },
    body: "Po të ngjit CV-në time më poshtë. Më thuaj 5 gjëra që janë të dobëta dhe si t'i përmirësoj, që të dukem më e besueshme dhe e fortë. Pastaj rishkruaj seksionin e përvojës. CV-ja ime: [ngjit tekstin].",
  },
  {
    id: "cv-cover-letter",
    category: "cv",
    icon: "Mail",
    title: { sq: "Letër motivimi", en: "Cover letter" },
    description: { sq: "E shkurtër, e sigurt dhe njerëzore.", en: "Short, confident and human." },
    body: "Më shkruaj një letër motivimi (cover letter) për pozicionin [pozicioni] në kompaninë [emri]. Pse më intereson: [arsyeja]. Çfarë sjell unë: [aftësitë/përvoja]. Toni: i sigurt, profesional, por njerëzor — jo i ftohtë.",
  },
  {
    id: "cv-interview-prep",
    category: "cv",
    icon: "MessagesSquare",
    title: { sq: "Përgatitu për intervistë", en: "Get ready for an interview" },
    description: { sq: "Pyetjet që mund të të bëjnë dhe si t'u përgjigjesh.", en: "The questions they might ask and how to answer." },
    body: "Më bëj 10 pyetjet më të zakonshme të intervistës për rolin [pozicioni], dhe pas çdo pyetjeje më jep një strukturë se si të përgjigjem. Pastaj luaj rolin e intervistuesit dhe bëmë pyetjet një nga një, duke më dhënë vlerësim pas çdo përgjigjeje time.",
  },
  {
    id: "cv-linkedin",
    category: "cv",
    icon: "Briefcase",
    title: { sq: "Profili yt në LinkedIn", en: "Your LinkedIn profile" },
    description: { sq: "Një titull dhe një përshkrim që të dallojnë.", en: "A headline and an 'About' that make you stand out." },
    body: "Më shkruaj një titull (headline) dhe një seksion 'About' për LinkedIn. Jam [profesioni], me përvojë në [fusha], dhe dua të tërheq [punëdhënës / klientë / mundësi]. Bëje që të dallohem por të mbetet autentik.",
  },

  // ---------- 3. Sukses, Qëllime dhe Disiplinë ----------
  {
    id: "goals-clarify",
    category: "goals",
    icon: "Target",
    title: { sq: "Çfarë do vërtet?", en: "What do you really want?" },
    description: { sq: "Pyetje që të ndihmojnë të kuptosh qëllimet e tua.", en: "Questions that help you understand your goals." },
    body: "Ndihem e humbur dhe nuk e di se çfarë dua të arrij. Më bëj 7 pyetje të thella, një nga një, që të më ndihmosh të kuptoj vlerat dhe qëllimet e mia të vërteta. Prit përgjigjen time para çdo pyetjeje të re.",
  },
  {
    id: "goals-dream-to-plan",
    category: "goals",
    icon: "CalendarCheck",
    title: { sq: "Nga ëndrra te plani", en: "From dream to plan" },
    description: { sq: "Ndaje qëllimin e madh në hapa të vegjël.", en: "Break the big goal into small steps." },
    body: "Qëllimi im i madh është: [përshkruaj]. Më ndihmo ta ndaj në qëllime vjetore, mujore dhe javore. Më jep një sistem të thjeshtë për të matur përparimin pa u mbingarkuar.",
  },
  {
    id: "goals-procrastination",
    category: "goals",
    icon: "Sparkles",
    title: { sq: "Mos e shtyr më", en: "Stop putting it off" },
    description: { sq: "Si ta nisësh sot, qoftë edhe për 15 minuta.", en: "How to start today, even for 15 minutes." },
    body: "E shtyj gjithmonë [detyra/projekti]. Më ndihmo të kuptoj pse e shtyj dhe më jep një metodë konkrete për ta filluar sot, edhe nëse kam vetëm 15 minuta.",
  },
  {
    id: "goals-morning-routine",
    category: "goals",
    icon: "Sun",
    title: { sq: "Mëngjesi yt i qetë", en: "Your calm morning" },
    description: { sq: "Një rutinë e thjeshtë për ta nisur ditën pa nxitim.", en: "A simple routine to start the day without rushing." },
    body: "Më ndihmo të ndërtoj një rutinë mëngjesi realiste që zgjat [sa minuta], duke pasur parasysh që kam [fëmijë / punë / përgjegjësi]. Dua të nis ditën me qetësi dhe fokus, jo me nxitim.",
  },

  // ---------- 4. Nënësi dhe Familje ----------
  {
    id: "mother-balance",
    category: "motherhood",
    icon: "HeartHandshake",
    title: { sq: "Punë dhe fëmijë, pa faj", en: "Work and children, without guilt" },
    description: { sq: "Si të gjesh ekuilibër dhe të jesh më e butë me veten.", en: "How to find balance and be gentler with yourself." },
    body: "Jam nënë e [numri] fëmijëve në moshën [moshat] dhe punoj [orari]. Ndihem fajtore që nuk po jap mjaftueshëm as në punë as në shtëpi. Më ndihmo me 5 mënyra praktike për të gjetur ekuilibër dhe një mënyrë mendimi më e shëndetshme rreth fajit.",
  },
  {
    id: "mother-explain-hard",
    category: "motherhood",
    icon: "MessageCircle",
    title: { sq: "Si t'i flasësh fëmijës për diçka të vështirë", en: "Explaining something hard to your child" },
    description: { sq: "Fjalë të buta, sipas moshës.", en: "Gentle words, age-appropriate." },
    body: "Më ndihmo si t'i shpjegoj fëmijës tim [moshë] temën [p.sh. divorci / vdekja / ndryshimi i shkollës] në një gjuhë të thjeshtë, të dashur dhe të përshtatshme për moshën.",
  },
  {
    id: "mother-activities",
    category: "motherhood",
    icon: "Sparkles",
    title: { sq: "Çfarë të bësh me fëmijët", en: "What to do with the kids" },
    description: { sq: "10 ide të lira për të luajtur e mësuar bashkë.", en: "10 cheap ideas to play and learn together." },
    body: "Më jep 10 aktivitete të lira ose të lira fare që mund t'i bëj me fëmijën [moshë] në shtëpi ose jashtë, që zhvillojnë [krijimtarinë / lëvizjen / të mësuarit].",
  },
  {
    id: "mother-emotions",
    category: "motherhood",
    icon: "Heart",
    title: { sq: "Kur humb durimin me fëmijët", en: "When you lose patience with the kids" },
    description: { sq: "Si të qetësohesh dhe ta rigjesh lidhjen.", en: "How to calm down and reconnect." },
    body: "Ndonjëherë humb durimin me fëmijët dhe pastaj ndihem keq. Më jep mënyra konkrete për të qetësuar veten në moment, dhe si të rikthej lidhjen me fëmijën pas një momenti të vështirë.",
  },
  {
    id: "mother-meal-plan",
    category: "motherhood",
    icon: "Utensils",
    title: { sq: "Menuja javore e familjes", en: "The family's weekly menu" },
    description: { sq: "Ushqime të thjeshta e të shëndetshme, me listë pazari.", en: "Simple, healthy meals, with a shopping list." },
    body: "Më ndërto një menu javore me ushqime të shëndetshme dhe të thjeshta për një familje me [numri] anëtarë. Buxhet i kufizuar. Përfshi një listë pazari të organizuar sipas kategorive.",
  },

  // ---------- 5. Vetëbesim, Mirëqenie dhe Kufij ----------
  {
    id: "conf-build",
    category: "confidence",
    icon: "Sparkles",
    title: { sq: "Beso te vetja", en: "Believe in yourself" },
    description: { sq: "Ushtrime të vogla javore, jo fjalë boshe.", en: "Small weekly exercises, not empty words." },
    body: "Më ndihmo të punoj me vetëbesimin tim. Lufta ime kryesore është [përshkruaj]. Më jep ushtrime praktike javore, jo motivim bosh, që me kalimin e kohës më ndihmojnë të besoj te vetja.",
  },
  {
    id: "conf-boundaries",
    category: "confidence",
    icon: "MessageCircle",
    title: { sq: "Vendos kufij me njerëzit", en: "Set boundaries with people" },
    description: { sq: "Si ta thuash 'kaq mjafton' me qetësi e respekt.", en: "How to say 'that's enough' calmly and respectfully." },
    body: "Kam vështirësi të vendos kufij me [familje / partner / shoqe / kolegë]. Situata: [përshkruaj]. Më jep fjalët e sakta për të vendosur një kufi me respekt por me qartësi.",
  },
  {
    id: "conf-self-talk",
    category: "confidence",
    icon: "Heart",
    title: { sq: "Mos i fol vetes ashpër", en: "Don't be harsh with yourself" },
    description: { sq: "Si t'i kthesh mendimet negative në fjalë më të mira.", en: "How to turn negative thoughts into kinder words." },
    body: "Shpesh i flas vetes ashpër dhe mendoj se nuk jam mjaftueshëm e mirë. Më ndihmo të njoh këto mendime dhe t'i kthej në mendime më të drejta e më të dhembshura. Më jep shembuj konkretë.",
  },
  {
    id: "conf-burnout",
    category: "confidence",
    icon: "Sun",
    title: { sq: "Kur je e rraskapitur", en: "When you're worn out" },
    description: { sq: "Një plan i butë për t'u çlodhur këto dy javë.", en: "A gentle plan to rest over the next two weeks." },
    body: "Ndihem e rraskapitur nga [puna / familja / gjithçka]. Më ndihmo të kuptoj sa e rëndë është situata dhe më jep një plan të butë rikuperimi për 2 javët e ardhshme, hap pas hapi.",
  },

  // ---------- 6. Financa dhe Pavarësi Ekonomike ----------
  {
    id: "fin-budget",
    category: "finance",
    icon: "Wallet",
    title: { sq: "Buxheti yt mujor", en: "Your monthly budget" },
    description: { sq: "Një ndarje e thjeshtë dhe disa mënyra për të kursyer.", en: "A simple split and a few ways to save." },
    body: "Më ndihmo të ndërtoj një buxhet mujor të thjeshtë. Të ardhurat: [shuma]. Shpenzimet kryesore: [listo]. Dua të kursej për [qëllimi]. Më jep një ndarje të qartë dhe 3 mënyra për të kursyer pa vuajtur shumë.",
  },
  {
    id: "fin-basics",
    category: "finance",
    icon: "Sparkles",
    title: { sq: "Paratë, shpjeguar thjesht", en: "Money, explained simply" },
    description: { sq: "Kursimi dhe ku të nisësh, pa fjalë të vështira.", en: "Saving and where to start, no hard words." },
    body: "Nuk di shumë për financat. Më shpjego me fjalë të thjeshta: si të kursej, si funksionon kursimi për emergjenca, dhe nga ku të filloj nëse dua të investoj një ditë. Pa terma të komplikuar.",
  },
  {
    id: "fin-independence",
    category: "finance",
    icon: "TrendingUp",
    title: { sq: "Pavarësia financiare", en: "Financial independence" },
    description: { sq: "Hapa të vegjël për të ndërtuar sigurinë tënde.", en: "Small steps to build your security." },
    body: "Dua të jem më e pavarur financiarisht nga [partneri / familja]. Situata ime: [përshkruaj]. Më jep një plan praktik që të ndërtoj sigurinë time financiare gradualisht.",
  },

  // ---------- 7. Sipërmarrje dhe Biznes i Vogël ----------
  {
    id: "biz-validate",
    category: "business",
    icon: "Lightbulb",
    title: { sq: "A ia vlen ideja jote?", en: "Is your idea worth it?" },
    description: { sq: "Kush janë klientët dhe çfarë të provosh para se të investosh.", en: "Who the customers are and what to test before investing." },
    body: "Kam një ide biznesi: [përshkruaj idenë]. Më ndihmo ta vlerësoj — kush janë klientët, çfarë problemi zgjidh, dhe çfarë duhet të testoj para se të investoj para. Bëhu e sinqertë me dobësitë.",
  },
  {
    id: "biz-online",
    category: "business",
    icon: "Rocket",
    title: { sq: "Nise biznesin online", en: "Start your business online" },
    description: { sq: "Ku ta shesësh, sa ta çmosh dhe si t'i gjesh klientët.", en: "Where to sell, how to price and how to find customers." },
    body: "Dua të shes [produkt/shërbim] online. Më ndihmo me hapat e parë: ku ta shes, si ta çmoj, dhe si t'i gjej klientët e parë me buxhet të vogël.",
  },
  {
    id: "biz-social-posts",
    category: "business",
    icon: "Sparkles",
    title: { sq: "Postime për rrjetet sociale", en: "Social media posts" },
    description: { sq: "Tekste tërheqëse që sjellin klientë.", en: "Catchy posts that bring customers." },
    body: "Më shkruaj 5 postime për [Instagram/Facebook] për biznesin tim që shet [produkt/shërbim]. Toni: [i ngrohtë / profesional / argëtues]. Çdo postim të mbyllet duke e ftuar klientin të blejë ose të shkruajë.",
  },
  {
    id: "biz-pricing",
    category: "business",
    icon: "Wallet",
    title: { sq: "Sa ta vendosësh çmimin", en: "How to set your price" },
    description: { sq: "Çmoje punën tënde drejt dhe thuaje pa drojë.", en: "Price your work fairly and say it without hesitation." },
    body: "Ofroj shërbimin [përshkruaj] dhe nuk di sa ta çmoj. Më ndihmo të kuptoj si ta vendos çmimin pa e nënçmuar punën time, dhe si t'ia komunikoj klientit me siguri.",
  },

  // ---------- 8. Regjim Ushqimor dhe Shëndet ----------
  {
    id: "health-bmi",
    category: "health",
    icon: "Heart",
    title: { sq: "Kupto BMI-në, pa u shqetësuar", en: "Understand your BMI, without worry" },
    description: { sq: "Vetëm një tregues — jo e gjithë historia jote.", en: "Just one indicator — not your whole story." },
    body: "Më ndihmo të llogaris indeksin e masës trupore (BMI). Gjatësia ime: [cm]. Pesha ime: [kg]. Më jep shifrën, më shpjego me fjalë të thjeshta se çfarë do të thotë, dhe më kujto që BMI është vetëm një tregues i përgjithshëm — jo e gjithë historia e shëndetit.",
  },
  {
    id: "health-balanced-week",
    category: "health",
    icon: "Utensils",
    title: { sq: "Ushqim i ekuilibruar për javën", en: "Balanced eating for the week" },
    description: { sq: "Balancë dhe shije, jo dietë e rreptë. Me ushqime shqiptare.", en: "Balance and taste, not a strict diet. With Albanian foods." },
    body: "Vepro si këshilltar/e ushqimi me ndjeshmëri. Më ndërto një menu javore të ekuilibruar dhe të qëndrueshme, jo dietë ekstreme. Jam [aktive / pak aktive] dhe qëllimi im është [të ndihem më mirë / më shumë energji / të ushqehem më shëndetshëm]. Përdor ushqime të zakonshme shqiptare dhe të përballueshme. Përfshi mëngjes, drekë, darkë dhe 1–2 ushqime të lehta. Fokusi: balancë dhe shije, jo privim.",
  },
  {
    id: "health-quick-cheap",
    category: "health",
    icon: "Utensils",
    title: { sq: "Ushqim i shpejtë e i lirë", en: "Quick and cheap food" },
    description: { sq: "10 vakte nën 20 minuta për gjithë familjen.", en: "10 meals under 20 minutes for the whole family." },
    body: "Kam pak kohë dhe buxhet të vogël. Më jep 10 vakte të shpejta, të shëndetshme dhe të lira që mund t'i përgatis në më pak se 20 minuta, të përshtatshme edhe për familjen.",
  },
  {
    id: "health-food-relationship",
    category: "health",
    icon: "Heart",
    title: { sq: "Paqe me ushqimin", en: "Peace with food" },
    description: { sq: "Pa rregulla të rrepta dhe pa faj.", en: "No strict rules and no guilt." },
    body: "Më ndihmo të ndërtoj një marrëdhënie më të qetë dhe pozitive me ushqimin, pa rregulla shumë të rrepta dhe pa faj. Më jep parime të thjeshta që mund t'i ndjek për një kohë të gjatë.",
  },

  // ---------- 9. Shkolla dhe Fëmijët në Shkollë ----------
  {
    id: "school-help-homework",
    category: "school",
    icon: "GraduationCap",
    title: { sq: "Ndihmoje fëmijën me mësimet", en: "Help your child with schoolwork" },
    description: { sq: "Me durim, pa stres dhe më me qejf.", en: "With patience, stress-free and more fun." },
    body: "Fëmija im është në klasën [klasa] dhe ka vështirësi me lëndën [lënda]. Më jep mënyra praktike dhe të durueshme për ta ndihmuar në shtëpi, pa e stresuar, dhe si ta bëj të mësuarit më tërheqës për të.",
  },
  {
    id: "school-teacher-talk",
    category: "school",
    icon: "MessageCircle",
    title: { sq: "Bisedë me mësuesin", en: "A talk with the teacher" },
    description: { sq: "Si ta nisësh që të ndihmojë fëmijën, jo të bëhet sherr.", en: "How to start it so it helps the child, not a fight." },
    body: "Dua të flas me mësuesin/en e fëmijës tim për [problemi: notat / sjellja / vështirësia]. Më ndihmo të përgatis çfarë të them, me një ton bashkëpunues, që biseda të ndihmojë fëmijën dhe jo të kthehet në konflikt.",
  },
  {
    id: "school-bullying",
    category: "school",
    icon: "HeartHandshake",
    title: { sq: "Kur fëmija ka probleme me shokët", en: "When your child has trouble with friends" },
    description: { sq: "Si t'i flasësh me dashuri dhe çfarë të bësh.", en: "How to talk lovingly and what to do." },
    body: "Fëmija im [moshë] po përballet me [bullizëm / përjashtim / grindje me shokët] në shkollë. Më ndihmo si t'i flas me dashuri, çfarë pyetjesh t'i bëj, dhe çfarë hapash mund të ndërmarr me shkollën.",
  },
  {
    id: "school-motivation",
    category: "school",
    icon: "Sparkles",
    title: { sq: "Kur fëmija s'ka qejf mësimi", en: "When your child has no motivation" },
    description: { sq: "Si ta mbështetësh pa e ngarkuar.", en: "How to support without pressure." },
    body: "Fëmija im ka humbur motivimin për shkollë ose stresohet shumë para provimeve. Më jep mënyra për ta mbështetur emocionalisht dhe për t'i ndërtuar besimin, pa presion të tepërt.",
  },
  {
    id: "school-day-schedule",
    category: "school",
    icon: "CalendarCheck",
    title: { sq: "Dita pas shkollës", en: "After-school day" },
    description: { sq: "Mësim, lojë, pushim dhe gjumë — të ekuilibruara.", en: "Homework, play, rest and sleep — balanced." },
    body: "Më ndihmo të ndërtoj një orar të qartë pas-shkolle për fëmijën [moshë]: kohë për detyra, lojë, pushim dhe gjumë. Realist dhe i ekuilibruar.",
  },

  // ---------- 10. Marrëdhëniet dhe Dashuria ----------
  {
    id: "rel-communication",
    category: "relationships",
    icon: "MessagesSquare",
    title: { sq: "Kuptohu më mirë me partnerin", en: "Understand each other better" },
    description: { sq: "Si ta thuash atë që ndien pa e fajësuar.", en: "How to say what you feel without blaming." },
    body: "Me partnerin tim shpesh keqkuptohemi rreth [tema]. Më ndihmo të kuptoj si ta shpreh atë që ndiej pa e fajësuar, dhe si të dëgjoj më mirë. Më jep edhe disa fraza konkrete që mund t'i përdor.",
  },
  {
    id: "rel-healthy",
    category: "relationships",
    icon: "Heart",
    title: { sq: "A është e shëndetshme lidhja ime?", en: "Is my relationship healthy?" },
    description: { sq: "Pyetje të buta, pa gjykim.", en: "Gentle questions, no judgement." },
    body: "Dua të reflektoj mbi marrëdhënien time. Më bëj disa pyetje të kujdesshme, një nga një, që të më ndihmosh të kuptoj çfarë funksionon, çfarë jo, dhe çfarë kam nevojë. Mos gjyko — vetëm ndihmë.",
  },
  {
    id: "rel-conflict",
    category: "relationships",
    icon: "HeartHandshake",
    title: { sq: "Si ta zgjidhësh një grindje", en: "How to resolve a fight" },
    description: { sq: "Shihe edhe nga ana tjetër dhe gjej qetësinë.", en: "See the other side and find calm." },
    body: "Kam një mosmarrëveshje me [partnerin / familjen / shoqen] për [situata]. Më ndihmo ta shoh edhe nga ana tjetër dhe më jep një mënyrë për ta zgjidhur me qetësi dhe respekt.",
  },
  {
    id: "rel-leaving",
    category: "relationships",
    icon: "Heart",
    title: { sq: "Kur mendon të largohesh", en: "When you think about leaving" },
    description: { sq: "Mendo qartë dhe, nëse vendos, largohu me dinjitet.", en: "Think clearly and, if you decide, leave with dignity." },
    body: "Mendoj se duhet të largohem nga një marrëdhënie që nuk më bën mirë. Më ndihmo të mendoj qartë, të kuptoj ndjenjat e mia, dhe nëse vendos të largohem, si ta bëj me siguri dhe dinjitet.",
  },
  {
    id: "rel-dating",
    category: "relationships",
    icon: "Sparkles",
    title: { sq: "Kur njeh dikë të ri", en: "When you meet someone new" },
    description: { sq: "Ji vetvetja dhe vër re sinjalet që në fillim.", en: "Be yourself and notice the signs early." },
    body: "Po nis të takoj njerëz të rinj dhe ndihem [nervoze / e pasigurt]. Më jep këshilla për të qenë vetvetja, çfarë të kërkoj te një person, dhe sinjale paralajmëruese që duhet t'i vë re herët.",
  },
  {
    id: "rel-self-love",
    category: "relationships",
    icon: "Heart",
    title: { sq: "Dashuria për veten", en: "Loving yourself" },
    description: { sq: "Ushtrime që të ndihmojnë ta duash veten.", en: "Exercises that help you love yourself." },
    body: "Më ndihmo të ndërtoj një marrëdhënie të mirë me veten — para se të kërkoj miratim te të tjerët. Më jep ushtrime praktike që forcojnë vlerësimin tim ndaj vetes.",
  },

  // ---------- 11. Miqësitë ----------
  {
    id: "friend-build",
    category: "friendships",
    icon: "Users",
    title: { sq: "Si të bësh dhe të mbash shoqe", en: "Making and keeping friends" },
    description: { sq: "Njih njerëz dhe ruaj lidhjet, pa u lodhur.", en: "Meet people and keep the bonds, without exhaustion." },
    body: "Si e rritur, e kam të vështirë të krijoj miqësi të reja ose t'i ruaj ato që kam. Situata ime: [përshkruaj]. Më jep mënyra praktike për të njohur njerëz, për të mbajtur lidhjet, dhe për të qenë një shoqe e mirë pa u lodhur.",
  },
  {
    id: "friend-toxic",
    category: "friendships",
    icon: "HeartHandshake",
    title: { sq: "Kur një shoqëri të lëndon", en: "When a friendship hurts you" },
    description: { sq: "Si ta kuptosh dhe si të largohesh.", en: "How to see it and how to step away." },
    body: "Kam një shoqe që më merr energji ose më lëndon: [përshkruaj]. Më ndihmo të kuptoj nëse marrëdhënia është e shëndetshme dhe, nëse jo, si të largohem ose vendos kufij me sjellje.",
  },
  {
    id: "friend-repair",
    category: "friendships",
    icon: "MessageCircle",
    title: { sq: "Si ta ndreqësh pas një grindjeje", en: "How to mend things after a fight" },
    description: { sq: "Çfarë t'i thuash që ta rregullosh me dinjitet.", en: "What to say to fix it with dignity." },
    body: "U grinda me një shoqe të ngushtë për [situata]. Më ndihmo të hap një bisedë riparuese — çfarë t'i them që ta ndreq pa humbur dinjitetin tim.",
  },

  // ---------- 12. Familja e Madhe ----------
  {
    id: "fam-boundaries",
    category: "extendedfamily",
    icon: "MessageCircle",
    title: { sq: "Kufij me familjen e madhe", en: "Boundaries with extended family" },
    description: { sq: "Ruaj paqen, por mbro edhe hapësirën tënde.", en: "Keep the peace, but protect your space too." },
    body: "Kam tension me [vjehrrën / familjen / kunatat] rreth [tema: fëmijët / shtëpia / vendimet]. Më ndihmo të ruaj paqen por edhe të mbroj hapësirën time, me respekt dhe pa konflikt të hapur.",
  },
  {
    id: "fam-partner-team",
    category: "extendedfamily",
    icon: "HeartHandshake",
    title: { sq: "Mes partnerit dhe familjes së tij", en: "Between your partner and his family" },
    description: { sq: "Si ta bisedoni që të jeni në një mendje.", en: "How to talk it through and be on the same page." },
    body: "Ndihem mes partnerit dhe familjes së tij. Më ndihmo si ta bisedoj këtë me partnerin, që të jemi ekip dhe vendimet t'i marrim së bashku.",
  },
  {
    id: "fam-fair-share",
    category: "extendedfamily",
    icon: "Users",
    title: { sq: "Ndani punët e shtëpisë drejt", en: "Sharing housework fairly" },
    description: { sq: "Si ta hapësh bisedën pa u dukur si ankesë.", en: "How to open the talk without sounding like a complaint." },
    body: "Pjesa më e madhe e punëve të shtëpisë dhe e kujdesit bie mbi mua. Më ndihmo të hap një bisedë për ndarjen më të drejtë të përgjegjësive, pa u dukur sikur ankohem.",
  },

  // ---------- 13. Gatim dhe Receta ----------
  {
    id: "cook-from-fridge",
    category: "cooking",
    icon: "Utensils",
    title: { sq: "Çfarë të gatuaj me këto që kam?", en: "What can I cook with what I have?" },
    description: { sq: "2–3 receta të thjeshta nga ato që ke në shtëpi.", en: "2–3 simple recipes from what's at home." },
    body: "Kam këto përbërës: [listo çfarë ke]. Më jep 2–3 receta të thjeshta që mund t'i gatuaj me to sot, me hapa të qartë.",
  },
  {
    id: "cook-traditional",
    category: "cooking",
    icon: "Utensils",
    title: { sq: "Receta shqiptare", en: "Albanian recipes" },
    description: { sq: "Përbërësit, sasitë dhe hapat — edhe për fillestare.", en: "Ingredients, amounts and steps — even for beginners." },
    body: "Më jep recetën e plotë të [p.sh. byrek / fërgesë / tavë kosi / petulla], me përbërësit, sasitë dhe hapat, të shpjeguara qartë edhe për fillestare.",
  },
  {
    id: "cook-meal-prep",
    category: "cooking",
    icon: "CalendarCheck",
    title: { sq: "Gatim një herë për gjithë javën", en: "Cook once for the whole week" },
    description: { sq: "Pak gatime që ruhen mirë, me listë pazari.", en: "A few dishes that keep well, with a shopping list." },
    body: "Më ndihmo të gatuaj në një ditë ushqim që zgjat gjithë javën për [numri] veta. Më jep një plan me 3–4 gatime që ruhen mirë dhe një listë pazari.",
  },
  {
    id: "cook-guests",
    category: "cooking",
    icon: "Gift",
    title: { sq: "Menu për mysafirë", en: "A menu for guests" },
    description: { sq: "Mbresëlënëse, por jo e komplikuar.", en: "Impressive, but not complicated." },
    body: "Kam mysafirë [numri] veta për [drekë / darkë]. Më ndihmo të planifikoj një meny mbresëlënëse por jo të komplikuar, me një ëmbëlsirë, dhe çfarë mund ta përgatis një ditë më parë.",
  },
  {
    id: "cook-kids-healthy",
    category: "cooking",
    icon: "Heart",
    title: { sq: "Ushqim që fëmijët e hanë me qejf", en: "Food kids eat happily" },
    description: { sq: "Të shëndetshme, edhe për ata që zgjedhin.", en: "Healthy, even for picky eaters." },
    body: "Më jep ide ushqimesh të shëndetshme që fëmijët i hanë me dëshirë, edhe ato që janë zgjedhëse me ushqimin.",
  },

  // ---------- 14. Shtëpia dhe Organizimi ----------
  {
    id: "home-cleaning",
    category: "home",
    icon: "Home",
    title: { sq: "Pastrim pa u lodhur", en: "Cleaning without exhaustion" },
    description: { sq: "Pak çdo ditë, jo gjithçka në fundjavë.", en: "A little each day, not everything on the weekend." },
    body: "Më ndihmo të ndërtoj një rutinë pastrimi realiste — pak çdo ditë në vend që të lodhem gjithçka në fundjavë. Kam [sa kohë] në dispozicion në ditë.",
  },
  {
    id: "home-declutter",
    category: "home",
    icon: "Sparkles",
    title: { sq: "Rregullo dhe pastro shtëpinë", en: "Tidy and declutter your home" },
    description: { sq: "Dhomë pas dhome, pa stres.", en: "Room by room, stress-free." },
    body: "Shtëpia ime është e mbushur me sende dhe nuk di nga t'ia nis. Më jep një plan dhomë-pas-dhome për të rregulluar dhe hequr tepricat pa stres.",
  },
  {
    id: "home-wardrobe",
    category: "home",
    icon: "Shirt",
    title: { sq: "Rregullo garderobën", en: "Organize your wardrobe" },
    description: { sq: "Çfarë të mbash, çfarë të heqësh dhe si t'i kombinosh.", en: "What to keep, what to remove and how to mix them." },
    body: "Më ndihmo të organizoj garderobën time: çfarë të mbaj, çfarë të heq, dhe si të krijoj kombinime të thjeshta nga ato që kam.",
  },

  // ---------- 15. Koha dhe Planifikimi ----------
  {
    id: "time-day-plan",
    category: "time",
    icon: "CalendarCheck",
    title: { sq: "Planifiko ditën pa u mbingarkuar", en: "Plan your day without overload" },
    description: { sq: "Një orar realist që lë vend edhe për pushim.", en: "A realistic schedule that leaves room to rest." },
    body: "Më ndihmo të planifikoj ditën time me [punë, fëmijë, shtëpi]. Më jep një orar realist që lë vend edhe për pushim, jo vetëm detyra.",
  },
  {
    id: "time-prioritize",
    category: "time",
    icon: "Target",
    title: { sq: "Çfarë është vërtet e rëndësishme", en: "What really matters" },
    description: { sq: "Renditi punët dhe hiq ato që s'duhen.", en: "Order your tasks and drop the ones you don't need." },
    body: "Po t'i shkruaj të gjitha gjërat që kam për të bërë: [listo]. Më ndihmo t'i rendis sipas rëndësisë dhe të heq ato që nuk janë vërtet të domosdoshme.",
  },
  {
    id: "time-for-self",
    category: "time",
    icon: "Heart",
    title: { sq: "Pak kohë vetëm për ty", en: "A little time just for you" },
    description: { sq: "Si të gjesh momente që janë vetëm të tuat.", en: "How to find moments that are only yours." },
    body: "Ndihem sikur jeta ime është vetëm detyra dhe nuk kam kohë për vete. Më ndihmo të gjej hapësira të vogla gjatë ditës që janë vetëm të miat.",
  },

  // ---------- 16. Kujdesi për Veten dhe Bukuria ----------
  {
    id: "self-skincare",
    category: "selfcare",
    icon: "Sparkles",
    title: { sq: "Kujdesi i thjeshtë për lëkurën", en: "Simple skincare" },
    description: { sq: "Pa produkte të shtrenjta e të panevojshme.", en: "No expensive, unnecessary products." },
    body: "Më ndihmo të ndërtoj një rutinë të thjeshtë dhe të përballueshme për lëkurën. Tipi im i lëkurës: [e thatë / e yndyrshme / e ndjeshme / e përzier]. Pa produkte të shtrenjta të panevojshme.",
  },
  {
    id: "self-style",
    category: "selfcare",
    icon: "Shirt",
    title: { sq: "Stili yt, me pak para", en: "Your style, on a budget" },
    description: { sq: "Si të krijosh një stil të bukur me ato që ke.", en: "How to build a lovely style with what you have." },
    body: "Dua të ndihem më e sigurt me veshjet. Stili që më pëlqen: [përshkruaj]. Më jep ide si të krijoj një stil personal të thjeshtë me pak copë cilësore.",
  },
  {
    id: "self-calm",
    category: "selfcare",
    icon: "Heart",
    title: { sq: "10 minuta vetëm për ty", en: "10 minutes just for you" },
    description: { sq: "Mënyra të vogla për t'u çlodhur, pa para.", en: "Small ways to relax, for free." },
    body: "Më jep 10 mënyra të vogla për t'u kujdesur për veten kur kam vetëm 10 minuta — pa para dhe pa pajisje speciale.",
  },

  // ---------- 17. Festa, Mysafirë dhe Dhurata ----------
  {
    id: "celeb-party",
    category: "celebrations",
    icon: "Gift",
    title: { sq: "Organizo një festë", en: "Plan a celebration" },
    description: { sq: "Ushqimi, dekori dhe çfarë të bësh — hap pas hapi.", en: "Food, decor and what to do — step by step." },
    body: "Po organizoj [ditëlindje / festë / mbledhje familjare] për [numri] veta me buxhet [shuma]. Më ndihmo me një plan: ushqimi, dekori, dhe çfarë të bëj kur, hap pas hapi.",
  },
  {
    id: "celeb-gifts",
    category: "celebrations",
    icon: "Gift",
    title: { sq: "Ide dhuratash", en: "Gift ideas" },
    description: { sq: "10 ide me kuptim, jo nga të zakonshmet.", en: "10 meaningful ideas, not the ordinary ones." },
    body: "Më jep 10 ide dhuratash për [personi: nënë / shoqe / fëmijë / partner] për [rasti]. Buxheti: [shuma]. Dua diçka me kuptim, jo të zakonshme.",
  },
  {
    id: "celeb-messages",
    category: "celebrations",
    icon: "MessageCircle",
    title: { sq: "Urime dhe mesazhe", en: "Wishes and messages" },
    description: { sq: "Një mesazh i ngrohtë për rastin që ke.", en: "A warm message for your occasion." },
    body: "Më shkruaj një mesazh të ngrohtë urimi për [personi] me rastin e [festa/ngjarja]. Toni: [i sinqertë / argëtues / prekës].",
  },

  // ---------- 18. Mësim dhe Rritje Personale ----------
  {
    id: "learn-new-skill",
    category: "learning",
    icon: "BookOpen",
    title: { sq: "Mëso diçka të re", en: "Learn something new" },
    description: { sq: "Një plan për fillestare dhe burime falas.", en: "A beginner plan and free resources." },
    body: "Dua të mësoj [aftësia: gjuhë e huaj / kompjuter / gatim / diçka tjetër]. Më ndërto një plan mësimi për fillestare me [sa kohë] në javë dhe burime falas.",
  },
  {
    id: "learn-reading-habit",
    category: "learning",
    icon: "BookOpen",
    title: { sq: "Lexo më shumë", en: "Read more" },
    description: { sq: "Si të gjesh kohë dhe libra që të pëlqejnë.", en: "How to find time and books you'll like." },
    body: "Dua të lexoj më shumë por nuk gjej kohë ose motivim. Më ndihmo të krijoj zakonin dhe më rekomando si të zgjedh libra që më përshtaten.",
  },
  {
    id: "learn-weekly-reflection",
    category: "learning",
    icon: "RefreshCw",
    title: { sq: "Reflektim çdo javë", en: "Reflect every week" },
    description: { sq: "5 pyetje që të ndihmojnë të rritesh.", en: "5 questions that help you grow." },
    body: "Bëhu si një ditar i drejtuar. Çdo javë bëmë 5 pyetje që më ndihmojnë të reflektoj mbi javën, çfarë mësova dhe çfarë dua të përmirësoj.",
  },
];
